# Generated by Django 3.2.9 on 2021-12-03 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=64, verbose_name='category name')),
            ],
        ),
        migrations.AddField(
            model_name='productitem',
            name='product_category',
            field=models.ManyToManyField(to='catalogapp.ProductCategory'),
        ),
    ]
