# Generated by Django 3.2.9 on 2021-12-08 21:39

import django.contrib.sites.managers
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('catalogapp', '0002_auto_20211203_2152'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='productcategory',
            managers=[
                ('objects', django.contrib.sites.managers.CurrentSiteManager('site')),
            ],
        ),
        migrations.AlterModelManagers(
            name='productitem',
            managers=[
                ('objects', django.contrib.sites.managers.CurrentSiteManager('site')),
            ],
        ),
        migrations.AddField(
            model_name='productcategory',
            name='site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sites.site'),
        ),
        migrations.AddField(
            model_name='productitem',
            name='site',
            field=models.ManyToManyField(to='sites.Site'),
        ),
    ]
